ALTER TABLE artikel
ADD COLUMN created_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN created_by BIGINT,
ADD COLUMN updated_by BIGINT,
ADD FOREIGN KEY (created_by) REFERENCES users(id),
ADD FOREIGN KEY (updated_by) REFERENCES users(id); 